from classes import *

deck = dict(
    preRotCharEx =  [
        Card("Charizard ex","sv4pt5-54","Pokémon",["Stage 2","Tera","ex"],"sv4pt5",54,"G"),
        Card("Charizard ex","sv4pt5-54","Pokémon",["Stage 2","Tera","ex"],"sv4pt5",54,"G"),
        Card("Charizard ex","sv4pt5-54","Pokémon",["Stage 2","Tera","ex"],"sv4pt5",54,"G"),
        Card("Charizard ex","sv3pt5-6","Pokémon",["Stage 2","ex"],"sv3pt5",6,"G"),
        Card("Charizard","pgo-10","Pokémon",["Stage 2"],"pgo",10,"F"),
        "Charizard",
        "Charmander",
        "Charmander",
        "Charmander",
        "Charmander",
        "Charmeleon",
        "Lumineon V",
        "Manaphy",
        "Pidgeot ex",
        "Pidgeot ex",
        "Pidgey",
        "Pidgey",
        "Rotom V",
        "Jirachi",
        "Radiant Greninja",
        "Artazon",
        "Arven",
        "Arven",
        "Arven",
        "Battle VIP Pass",
        "Battle VIP Pass",
        "Battle VIP Pass",
        "Battle VIP Pass",
        "Boss' Orders",
        "Boss' Orders",
        "Boss' Orders",
        "Collapsed Stadium",
        "Counter Catcher",
        "Feather ball",
        "Forest Seal Stone",
        "Iono",
        "Iono",
        "Iono",
        "Lost City",
        "Lost Vacuum",
        "Nest Ball",
        "Professor's Research",
        "Rare Candy",
        "Rare Candy",
        "Rare Candy",
        "Rare Candy",
        "Super Rod",
        "Super Rod",
        "Technical Machine: Devolution",
        "Ultra Ball",
        "Ultra Ball",
        "Ultra Ball",
        "Vitality Band",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy",
        "Basic Fire Energy"
    ]
)
